# config/_default/languages.zh.toml

title = "Coffee Weekly"
languageCode = "zh-cn"
languageName = "中文"
weight = 1

[params]
  displayName = "中文"
  isoCode = "zh"
  rtl = false
  dateFormat = "2 January 2006"
  logo = "img/logo.png"
  # secondaryLogo = "img/secondary-logo.png"
  description = "☕︎ Coffee Weekly is my blog for sharing interesting things that i've found."
  #copyright = "Copy, _right?_ :thinking_face:"
  
[author]
  name = "uzvg"
  image = "img/author.png"
  headline = "TO BE DIFFERENT!"
  bio = "A little bit about me"
  links = [
    { mail = "http://mail.qq.com/cgi-bin/qm_share?t=qm_mailme&email=UmNma2VrY2NramESIyN8MT0-" },
    { wechat = "https://uzvg.site" },
    { zhihu = "https://www.zhihu.com/people/yan-qiu-20-48" },
    { github = "https://github.com/uzvg/coffee-weekly" },
    { x-twitter = "https://twitter.com/jiang_uzvg" },
    { telegram = "https://t.me/uczmvgnk" },
    { link = "https://uzvg.site" },
    #{ amazon = "https://www.amazon.com/hz/wishlist/ls/wishlist-id" },
    #{ apple = "https://www.apple.com" },
    #{ blogger = "https://username.blogspot.com/" },
    #{ bluesky = "https://bsky.app/profile/username" },
    #{ codepen = "https://codepen.io/username" },
#     { dev = "https://dev.to/username" },
#     { discord = "https://discord.gg/invitecode" },
#     { dribbble = "https://dribbble.com/username" },
#     { facebook = "https://facebook.com/username" },
#     { flickr = "https://www.flickr.com/photos/username/" },
#     { foursquare = "https://foursquare.com/username" },
#     { gitlab = "https://gitlab.com/username" },
#     { google = "https://www.google.com/" },
#     { hashnode = "https://username.hashnode.dev" },
#     { instagram = "https://instagram.com/username" },
#     { itch-io = "https://username.itch.io" },
#     { keybase = "https://keybase.io/username" },
#     { kickstarter = "https://www.kickstarter.com/profile/username" },
#     { lastfm = "https://lastfm.com/user/username" },
#     { linkedin = "https://linkedin.com/in/username" },
#     { mastodon = "https://mastodon.instance/@username" },
#     { medium = "https://medium.com/username" },
#     { microsoft = "https://www.microsoft.com/" },
#     { orcid = "https://orcid.org/userid" },
#     { patreon = "https://www.patreon.com/username" },
#     { pinterest = "https://pinterest.com/username" },
#     { reddit = "https://reddit.com/user/username" },
#     { researchgate = "https://www.researchgate.net/profile/username" },
#     { slack = "https://workspace.url/team/userid" },
#     { snapchat = "https://snapchat.com/add/username" },
#     { soundcloud = "https://soundcloud.com/username" },
#     { stack-overflow = "https://stackoverflow.com/users/userid/username" },
#     { steam = "https://steamcommunity.com/profiles/userid" },
#     { threads = "https://www.threads.net/@username" },
#     { tiktok = "https://tiktok.com/@username" },
#     { tumblr = "https://username.tumblr.com" },
#     { twitch = "https://twitch.tv/username" },
#     { twitter = "https://twitter.com/username" },
#     { whatsapp = "https://wa.me/phone-number" },
#     { youtube = "https://youtube.com/username" },
#     { ko-fi = "https://ko-fi.com/username" },
  ]